# Copyright 2026 Escodoo
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Regenerate data/ir_attachment_pre.xml from the downloaded binaries."""
# This is a standalone maintenance script, not Odoo server code.
# pylint: disable=print-used

import mimetypes
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parent.parent
BINARY_DIR = MODULE_DIR / "static" / "src" / "binary" / "ir_attachment"
TARGET = MODULE_DIR / "data" / "ir_attachment_pre.xml"

HEADER = """<?xml version="1.0" encoding="utf-8" ?>
<odoo noupdate="1">
    <!-- Generated by tools/build_attachment_xml.py, do not edit by hand. -->
"""
FOOTER = "</odoo>\n"

RECORD = """    <record id="{xml_id}" model="ir.attachment">
        <field name="name">{file_name}</field>
        <field name="mimetype">{mimetype}</field>
        <field
            name="datas"
            type="base64"
            file="split_website/static/src/binary/ir_attachment/{file_name}"
        />
        <field name="public" eval="True" />
    </record>
"""


def main():
    mimetypes.add_type("image/svg+xml", ".svg")
    chunks = [HEADER]
    for path in sorted(BINARY_DIR.iterdir()):
        if path.name.startswith("."):
            continue
        mimetype = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        chunks.append(
            RECORD.format(
                xml_id=path.stem,
                file_name=path.name,
                mimetype=mimetype,
            )
        )
    chunks.append(FOOTER)
    TARGET.write_text("".join(chunks), encoding="utf-8")
    print(f"{TARGET.relative_to(MODULE_DIR)}: {len(chunks) - 2} attachments")


if __name__ == "__main__":
    main()
